_wandb:
    value:
        cli_version: 0.21.1
        e:
            xm8ke7371umdwxdu9gqmbk2t138hkyj1:
                args:
                    - --exp_name
                    - alpha_racer_multi
                    - --start_ep
                    - "151"
                    - --end_ep
                    - "175"
                    - --use_wandb
                codePath: car_ros2/car_ros2/multi_car_blocking.py
                codePathLocal: multi_car_blocking.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "123254587392"
                        used: "86222716928"
                email: mahiensanklechaa555.24@kgpian.iitkgp.ac.in
                executable: /usr/bin/python3
                git:
                    commit: 9e0ffc8b326a5360eeed9fea1eba7aad30168039
                    remote: git@github.com:sastry-group/alpha-RACER.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-a47e145e-8fd3-82c1-1217-e3e26b0de94e
                host: MahinSanklecha
                memory:
                    total: "16063684608"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/mahin-sanklecha/alpha-RACER/car_ros2/car_ros2/multi_car_blocking.py
                python: CPython 3.10.12
                root: /home/mahin-sanklecha/alpha-RACER/car_ros2/car_ros2
                startedAt: "2025-08-31T07:09:16.566460Z"
                writerId: xm8ke7371umdwxdu9gqmbk2t138hkyj1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 12
            "2":
                - 1
                - 12
            "3":
                - 13
            "4": 3.10.12
            "5": 0.21.1
            "10":
                - 20
            "12": 0.21.1
            "13": linux-x86_64
