_wandb:
    value:
        cli_version: 0.21.1
        e:
            dlzv2aj1p56b6pyy65pr8l99upru9z6v:
                codePath: car_ros2/car_ros2/wandb_merge.py
                codePathLocal: wandb_merge.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "123254587392"
                        used: "86191423488"
                email: mahiensanklechaa555.24@kgpian.iitkgp.ac.in
                executable: /usr/bin/python3
                git:
                    commit: 9e0ffc8b326a5360eeed9fea1eba7aad30168039
                    remote: git@github.com:sastry-group/alpha-RACER.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-a47e145e-8fd3-82c1-1217-e3e26b0de94e
                host: MahinSanklecha
                memory:
                    total: "16063684608"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/mahin-sanklecha/alpha-RACER/car_ros2/car_ros2/wandb_merge.py
                python: CPython 3.10.12
                root: /home/mahin-sanklecha/alpha-RACER/car_ros2/car_ros2
                startedAt: "2025-08-31T07:45:46.587337Z"
                writerId: dlzv2aj1p56b6pyy65pr8l99upru9z6v
        m: []
        python_version: 3.10.12
        t:
            "4": 3.10.12
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
