apiVersion: v1
kind: Pod
metadata:
  name: ctun-server
  labels:
    app: ctun-server
spec:
  containers:
    - name: k8s-ctun-server
      image: dspace/ctun/local-server:23.1.0
      imagePullPolicy: Never
      env:
        - name: ETH_DEVICE 
          value: "eth0"
        - name: SERVER_PORT 
          value: "1723"
        - name: CMD_OPTIONS 
          value: ""
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        capabilities:
          add:
            - NET_ADMIN

      volumeMounts:
      - mountPath: /dev/net/tun
        name: dev-tun
        readOnly: false
  volumes:
    - name: dev-tun
      hostPath:
        path: /dev/net/tun
        type: CharDevice
