apiVersion: v1
kind: Service
metadata:
  name: ctun-service
spec:
  type: NodePort
  selector:
    app: ctun-server
  ports:
    - name: ctun-service
      port: 1723
      targetPort: 1723
      nodePort: 31723
      protocol: UDP