networks:
    mynetwork:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.0.0/16
services:
    ctun:
        image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_ctun:2024-11-13
        container_name: ctun
        ports:
            - 1723:1723/udp
        cap_add:
            - NET_ADMIN
            - SYS_PTRACE
        networks:
            mynetwork:
                ipv4_address: 10.6.0.8
        depends_on:
            veos:
                condition: service_started

    veos:
        image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_veos23a:2024-11-13
        container_name: veos
        ports:
            - 7216:7216
            - 22222:22222
        cap_add:
            - SYS_PTRACE
        expose:
            - 1337/udp
        environment:
            - DS_CMU_SERVER=license-server-lb-37903434.eu-central-1.elb.amazonaws.com
            # - DS_VEOS_LOAD_OSA=/home/dspace/VEOS/ASM_Traffic.osa
            - DS_VEOS_LOAD_OSA=/home/dspace/VEOS_1ms/ASM_Traffic.osa
            - DS_VEOS_REMOTE_CAPABLE=1
        shm_size: 256m
        networks:
            mynetwork:
                ipv4_address: 10.6.0.2
        depends_on:
            vesi:
                condition: service_started

    vesi:
        image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_vesi:2024-11-13
        container_name: vesi
        restart: always
        ports:
            - 12345:12345
        tty: true
        networks:
            mynetwork:
                ipv4_address: 10.6.0.3

    sut_te_bridge:
        # image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_sut_te_bridge_dev:2024-11-13
        image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_sut_te_bridge:2024-11-13
        container_name: sut_te_bridge
        restart: always
        environment:
            - VESI_IP=10.6.0.3
            - ASM_IP=10.6.0.2
            # - SIM_CLOCK_MODE=false
            - SIM_CLOCK_MODE=true
            # - PUB_ITV_RACE_CONTROL_DATA=10
            # - PUB_ITV_VEHICLE_DATA=10
            # - PUB_ITV_POWER_TRAIN_DATA=10
            # - PUB_ITV_GROUND_TRUTH_ARRAY=10
            # - PUB_ITV_NOVATEL_DATA=10
            # - PUB_ITV_FOXGLOVE_MAP=10
        cap_add:
            - SYS_ADMIN
            - DAC_READ_SEARCH
            - SYS_PTRACE
        # volumes:
        #     - ./sut-te-bridge/dSPACE-IAC-sut-te-bridge/ros2_bridge_ws:/root/ros2_bridge_ws
        #     - ./sut-te-bridge/runtime_scripts:/root/runtime_scripts
        networks:
            mynetwork:
                ipv4_address: 10.6.0.4
        depends_on:
            veos:
                condition: service_healthy

    foxglove_bridge:
        image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_sut_te_bridge_foxglove:2024-11-13
        container_name: foxglove_bridge
        ports:
            - 8765:8765/tcp
        networks:
            mynetwork:
                ipv4_address: 10.6.0.5
        depends_on:
            veos:
                condition: service_healthy

    uva_example_driving_stack:
        build: .
        # image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_uva_demo_av_stack_dev:2024-11-13
        image: myapp:latest
        container_name: driving_stack
        volumes:
            - ./gt_controller:/root/gt_controller
            - ./uva-stack/sample_controller/runtime_scripts:/root/runtime_scripts
        environment:
            - SIM_CLOCK_MODE=true
        networks:
            mynetwork:
                ipv4_address: 10.6.0.7
        depends_on:
            veos:
                condition: service_healthy
